/**
 * @fileoverview gRPC-Web generated client stub for image_server
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.3
// source: image_operation.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.image_server = require('./image_operation_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.image_server.ImageOperationServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.image_server.ImageOperationServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.image_server.ImageOperation,
 *   !proto.image_server.ImageOperationResponse>}
 */
const methodDescriptor_ImageOperationService_GetImageOperation = new grpc.web.MethodDescriptor(
  '/image_server.ImageOperationService/GetImageOperation',
  grpc.web.MethodType.UNARY,
  proto.image_server.ImageOperation,
  proto.image_server.ImageOperationResponse,
  /**
   * @param {!proto.image_server.ImageOperation} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.image_server.ImageOperationResponse.deserializeBinary
);


/**
 * @param {!proto.image_server.ImageOperation} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.image_server.ImageOperationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.image_server.ImageOperationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.image_server.ImageOperationServiceClient.prototype.getImageOperation =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/image_server.ImageOperationService/GetImageOperation',
      request,
      metadata || {},
      methodDescriptor_ImageOperationService_GetImageOperation,
      callback);
};


/**
 * @param {!proto.image_server.ImageOperation} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.image_server.ImageOperationResponse>}
 *     Promise that resolves to the response
 */
proto.image_server.ImageOperationServicePromiseClient.prototype.getImageOperation =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/image_server.ImageOperationService/GetImageOperation',
      request,
      metadata || {},
      methodDescriptor_ImageOperationService_GetImageOperation);
};


module.exports = proto.image_server;

